# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DA8Xs2The77_cKLAZFe3Wuwsq300CVDt
"""

import numpy as np
from scipy.stats import bernoulli

sample_size = 100000
prob_A =0.5
prob_B = 0.6
prob_A_or_B= 0.7


sample_A = bernoulli.rvs(size = sample_size , p = prob_A)
sample_B = bernoulli.rvs(size = sample_size , p = prob_B)
sample_A_or_B = bernoulli.rvs(size = sample_size , p = prob_A_or_B)
 
A =0
B = 0
A_or_B=0

for i in range(sample_size):
  if sample_A[i]==1:
     A+=1

for i in range(sample_size):
  if sample_B[i]==1:
     B+=1  
for i in range(sample_size):
  if sample_A_or_B[i]==1:
     A_or_B+=1  
 
calc_prob_A=A/sample_size
calc_prob_B=B/sample_size
calc_prob_A_or_B=A_or_B/sample_size

prob_A_and_B = prob_A + prob_B - prob_A_or_B
calc_prob_A_and_B = calc_prob_A + calc_prob_B - calc_prob_A_or_B
print("The probability that it will rain today and tomorrow :",prob_A_and_B)
print("The probability that it will rain today and tomorrow :",calc_prob_A_and_B)